# This is a basic workflow to help you get started with Actions

name: Deploy website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: |
          npm install 
          .\build.ps1
          git config --global user.email "github@example.com"
          git config --global user.name "Github Bot"
          git checkout -b main
          git add .
          git commit -m "Web Deployement"
          git show-ref
          git status
          git remote get-url --all origin
          git push origin main --force
      
      #- name: Push to the repo
       # uses: stefanzweifel/git-auto-commit-action@v4
       # with: 
        #  branch: main
